#!/usr/bin/env node
/**
 * generate-pages.js — Build paper pages from pages-data.json
 *
 * Reads: ~/conversations/tambapanni-project/output/pages-data.json
 *        (generated by extract_pages_data.sh using LLM)
 *
 * Writes: papers/history.qmd, papers/positioned.qmd, updates index.qmd
 *
 * This script is deterministic — no LLM calls. The LLM step is upstream
 * in extract_pages_data.sh. This script only formats JSON into Quarto.
 *
 * Usage: node generate-pages.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

const PROJECT_DIR = path.join(process.env.HOME, 'conversations/tambapanni-project');
const PAGES_DIR = path.join(process.env.HOME, 'conversations/tambapanni-pages');
const DATA_FILE = path.join(PROJECT_DIR, 'output/pages-data.json');

const DOCS = {
  history: {
    pdf: 'pdf/1.%20Tambapanni_History_Without_Borders.pdf',
    pdfUrl: 'https://tambapanni.github.io/papers/pdf/1. Tambapanni_History_Without_Borders.pdf',
    url: 'https://tambapanni.github.io/papers/history.html',
    categories: '[political-economy, state-building, historiography, sri-lanka]',
    partNum: 1,
    companion: null,
  },
  positioned: {
    pdf: 'pdf/2.%20Tambapanni_Positioned.pdf',
    pdfUrl: 'https://tambapanni.github.io/papers/pdf/2. Tambapanni_Positioned.pdf',
    url: 'https://tambapanni.github.io/papers/positioned.html',
    categories: '[political-economy, state-building, institutional-reform, sri-lanka]',
    partNum: 2,
    companion: 'history',
  },
};

// ── Read existing DOI from .qmd ─────────────────────────────────────────

function getExistingDoi(qmdPath) {
  if (!fs.existsSync(qmdPath)) return null;
  const content = fs.readFileSync(qmdPath, 'utf8');
  const m = content.match(/doi:\s*(10\.\d+\/\S+)/);
  return m ? m[1] : null;
}

// ── Generate .qmd ───────────────────────────────────────────────────────

function generateQmd(key, data, docConfig) {
  const qmdPath = path.join(PAGES_DIR, 'papers', `${key}.qmd`);
  const existingDoi = getExistingDoi(qmdPath);

  const title = `${data.title}${data.subtitle ? ': ' + data.subtitle : ''}`;
  const yamlAbstract = data.abstract.split('\n').map(l => '  ' + l).join('\n');

  // DOI links
  const doiLine = existingDoi
    ? `[DOI: ${existingDoi}](https://doi.org/${existingDoi}){.btn .btn-outline-secondary}`
    : '[DOI (coming soon)](#){.btn .btn-outline-secondary title="Coming soon"}';
  const doiFm = existingDoi ? `\n  doi: ${existingDoi}` : '';

  // Key arguments or sections
  let keySection;
  if (data.key_arguments && data.key_arguments.length > 0) {
    keySection = '### Key Arguments\n\n' +
      data.key_arguments.map(a => `- **${a.bold}** ${a.text}`).join('\n\n');
  }
  if (data.key_sections && data.key_sections.length > 0) {
    const sectionsBlock = '### Key Sections\n\n' +
      data.key_sections.map(s => `- **${s}**`).join('\n');
    keySection = keySection ? keySection + '\n\n' + sectionsBlock : sectionsBlock;
  }

  // Frameworks
  const frameworkSection = data.frameworks && data.frameworks.length > 0
    ? '### Frameworks Applied\n\n' +
      data.frameworks.map(f => `- **${f.name}** — ${f.desc}`).join('\n')
    : '';

  // Companion
  const companionLine = docConfig.companion
    ? `\n**Companion to:** [Tambapanni: A History Without Borders](${docConfig.companion}.qmd)\n`
    : '';

  return `---
title: "${title}"
subtitle: "${data.tagline || data.subtitle || ''}"
date: 2026-03-01
author:
  - name: Ananthaneshan Elampoornan
    orcid: 0009-0004-9181-2270
google-scholar: true
citation:
  type: article
  container-title: "Tambapanni White Paper Series"
  issued: 2026-03
  url: ${docConfig.url}
  pdf-url: ${docConfig.pdfUrl}${doiFm}
categories: ${docConfig.categories}
abstract: |
${yamlAbstract}
---

## Part ${docConfig.partNum} of the Tambapanni Series

**Status:** Complete · ${data.version} · ${data.date}
${companionLine}
${keySection || ''}

${frameworkSection}

### Downloads

[Download PDF](${docConfig.pdf}){.btn .btn-primary} ${doiLine}

### Citation

${data.cite_as}

---

[← Back to series overview](../index.qmd)
`;
}

// ── Update index.qmd ────────────────────────────────────────────────────

function updateIndex(allData) {
  const indexPath = path.join(PAGES_DIR, 'index.qmd');
  if (!fs.existsSync(indexPath)) return;

  let index = fs.readFileSync(indexPath, 'utf8');

  // Update versions
  for (const [key, data] of Object.entries(allData)) {
    if (key === 'generated') continue;
    const titlePattern = key === 'history'
      ? 'History Without Borders'
      : 'Tambapanni Positioned';
    const versionRegex = new RegExp(
      `(${titlePattern}[\\s\\S]*?Complete · )v[0-9.]+`
    );
    index = index.replace(versionRegex, `$1${data.version}`);
  }

  fs.writeFileSync(indexPath, index);
}

// ── Main ────────────────────────────────────────────────────────────────

if (!fs.existsSync(DATA_FILE)) {
  console.error(`Error: ${DATA_FILE} not found.`);
  console.error('Run: ./tambapanni.sh extract-pages-data');
  process.exit(1);
}

const allData = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));

console.log('Building paper pages from pages-data.json...\n');
console.log(`  Data generated: ${allData.generated || 'unknown'}`);

for (const [key, docConfig] of Object.entries(DOCS)) {
  const data = allData[key];
  if (!data) {
    console.error(`  Warning: no data for ${key}`);
    continue;
  }

  const qmd = generateQmd(key, data, docConfig);
  const qmdPath = path.join(PAGES_DIR, 'papers', `${key}.qmd`);
  fs.writeFileSync(qmdPath, qmd);
  console.log(`  ${key}.qmd: ${qmd.split('\n').length} lines (${data.version})`);
  console.log(`    Abstract: ${data.abstract.substring(0, 70)}...`);
  console.log(`    Arguments: ${(data.key_arguments || []).length} items`);
  console.log(`    Frameworks: ${(data.frameworks || []).map(f => f.name).join(', ')}`);
}

updateIndex(allData);
console.log(`\n  index.qmd: versions updated`);
console.log('\nDone.');
